name: trendz_customer
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl_phone_field: ^3.2.0
  provider: ^6.1.2
  dio: ^5.7.0
  iconsax: ^0.0.8
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  shared_preferences: ^2.3.3
  flutter_launcher_icons: ^0.14.4
  android_intent_plus: ^5.2.0
  url_launcher: ^6.3.1
  lottie: ^3.2.0
  qr_flutter: ^4.1.0
  google_maps_flutter: ^2.10.0
  flutter_secure_storage: ^9.2.2
  carousel_slider: ^5.0.0
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to

  flutter_lints: ^4.0.0
 
flutter_icons:                     
  android: true
  ios: true
  image_path: "lib/assets/images/logo.png" 
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/images/logo.png"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/



